# Generated by Django 5.0.2 on 2024-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='mobile',
        ),
        migrations.AddField(
            model_name='custom',
            name='email',
            field=models.EmailField(default=1231, max_length=254),
            preserve_default=False,
        ),
    ]
