# Generated by Django 5.0.2 on 2024-02-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_custom_mobile_custom_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='email',
        ),
    ]
