# Generated by Django 5.0.2 on 2024-02-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_custom_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='profile_pic',
            field=models.ImageField(blank=True, default='main\\static\\profile_pic\\default.png', null=True, upload_to='main\\static\\profile_pic'),
        ),
    ]
