# Generated by Django 5.0.2 on 2024-04-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_task_completed_remove_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2'), ('choice3', 'Choice 3'), ('choice4', 'Choice 4')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True/False Question')], default='MCQ', max_length=10),
        ),
    ]
