# Generated by Django 5.0.2 on 2024-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_correct_answer_alter_task_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True/False Question'), ('OQ', 'Open Question')], default='MCQ', max_length=10),
        ),
    ]
