# Generated by Django 5.0.2 on 2024-04-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='completed_tasks',
            field=models.ManyToManyField(related_name='completed_by', to='main.task'),
        ),
    ]
