# Generated by Django 5.0.2 on 2024-02-26 17:31

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_custom_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default.png', null=True, upload_to=main.models.generate_filename),
        ),
    ]
