# Generated by Django 5.0.2 on 2024-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_custom_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='completed_tasks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custom',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
