# Generated by Django 5.0.2 on 2024-04-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_classroomprogress_progress_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassroomProgress',
        ),
    ]
