# Generated by Django 5.0.2 on 2024-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_classroomprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='completed_tasks_count',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='custom',
            name='classroom_progress',
            field=models.ManyToManyField(related_name='user_progress', to='main.classroomprogress'),
        ),
    ]
