# Generated by Django 5.0.2 on 2024-04-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_custom_completed_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='classroom_progress',
        ),
    ]
