# Generated by Django 5.0.6 on 2024-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_image_topic_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('choice1', 'Таңдау 1'), ('choice2', 'Таңдау 2'), ('choice3', 'Таңдау 3'), ('choice4', 'Таңдау 4')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Бірнеше Таңдау Туралы Сұрақ'), ('TF', 'Шын / Жалған Сұрақ'), ('OQ', 'Ашық Сұрақ')], default='MCQ', max_length=10),
        ),
    ]
