# Generated by Django 5.0.4 on 2024-06-13 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_image_topic_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('choice1', 'Таңдау 1'), ('choice2', 'Таңдау 2'), ('choice3', 'Таңдау 3'), ('choice4', 'Таңдау 4')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Бірнеше Таңдау Туралы Сұрақ'), ('TF', 'Шын / Жалған Сұрақ'), ('OQ', 'Ашық Сұрақ')], default='MCQ', max_length=10),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
