# Generated by Django 5.0.4 on 2024-06-13 05:51

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_task_correct_answer_alter_task_question_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=main.models.generate_video_filename)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='videos',
            field=models.ManyToManyField(blank=True, to='main.video'),
        ),
    ]
