# Generated by Django 5.0.6 on 2024-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
